(list-packages)
(package-install 'auto-complete)
(package-install 'color-theme-sanityinc-tomorrow)
(package-install 'company)
(package-install 'eacl)
(package-install 'evil)
(package-install 'fiplr)
(package-install 'flycheck)
(package-install 'helm-ag)
(package-install 'helm-ls-git)
(package-install 'helm-projectile)
(package-install 'magit)
(package-install 'projectile)
(package-install 'sr-speedbar)
(package-install 'web-mode)
(package-install 'w3m)
(package-install 'elfeed)
