(list-packages)q
(package-install 'ace-jump-mode)
(package-install 'auto-complete)
(package-install 'autopair)
(package-install 'color-theme-sanityinc-tomorrow)
(package-install 'eacl)
(package-install 'evil)
(package-install 'fiplr)
(package-install 'helm-ag)
(package-install 'helm-ls-git)
(package-install 'helm-projectile)
(package-install 'projectile)
(package-install 'sr-speedbar)
(package-install 'web-mode)